FROM golang:1.14-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

WORKDIR /go/go-galaxy
COPY . .

ARG GOPROXY
RUN go mod download
RUN make galaxy



FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY --from=builder /go/go-galaxy/build/galaxy /

EXPOSE 5050 18545 18546 18547 19090

ENTRYPOINT ["/galaxy"]
